# Generated by Django 4.0 on 2021-12-18 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('capacity', models.IntegerField()),
                ('creation_date', models.DateField(verbose_name='creation date')),
                ('modification_date', models.DateField(verbose_name='modification date')),
                ('content', models.ManyToManyField(related_name='+', to='chest.Item')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chest.location')),
            ],
        ),
        migrations.CreateModel(
            name='Barcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=64)),
                ('creation_date', models.DateField(verbose_name='creation date')),
                ('modification_date', models.DateField(verbose_name='modification date')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chest.item')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='container',
            field=models.ManyToManyField(related_name='+', to='chest.Container'),
        ),
    ]
