# Generated by Django 4.0 on 2021-12-18 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chest', '0002_location_container_barcode_item_container'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarcodeTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
            ],
        ),
        migrations.AddField(
            model_name='barcode',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chest.barcodetypes'),
        ),
    ]
