# Generated by Django 4.0 on 2021-12-18 15:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chest', '0003_barcodetypes_barcode_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='barcodetypes',
            name='creation_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='creation date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='barcodetypes',
            name='modification_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='modification date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='creation_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='creation date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='modification_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='modification date'),
            preserve_default=False,
        ),
    ]
